name: "List Fuzz Tests of Go"
description: "List Fuzz Tests of Go"
author: "ICHINOSE Shogo"

inputs:
  packages:
    required: false
    description: "This is an optional parameter that lets you specify the Go packages for which you want to list the fuzz tests. By default, it targets all packages in your project (`./...``)."
    default: "./..."
  working-directory:
    required: false
    description: "This is also an optional parameter that allows you to specify a working directory. The default is the root directory (`.`)."
    default: "."
  tags:
    required: false
    description: "A comma-separated list of additional build tags to consider satisfied during the build. It is equivalent to the `-tags` flag of the `go test` command."
    default: ""

outputs:
  fuzz-tests:
    description: "JSON-encoded list of all the fuzz tests for the specified Go packages."

runs:
  using: "node16"
  main: "../dist/list/index.js"
