name: "Run Fuzz Tests of Go"
description: "Run Fuzz Tests of Go"
author: "ICHINOSE Shogo"

inputs:
  repository:
    description: "Repository name with owner. For example, shogo82148/actions-go-fuzz."
    required: true
    default: ${{ github.repository }}
  token:
    description: "The GitHub token for the repository."
    required: true
    default: ${{ github.token }}
  packages:
    required: false
    description: "package name to list fuzz tests"
    default: "./..."
  working-directory:
    required: false
    description: "working directory"
    default: "."
  fuzz-regexp:
    required: false
    description: "Run the fuzz test matching the regular expression. Corresponds to the `-fuzz` flag for the `go test` command."
    default: "^Fuzz"
  fuzz-time:
    description: "Fuzz target iteration duration, specified as a `time.Duration` (for example `1h30s`). Corresponds to `-fuzztime` flag for the `go test` command. Ensure this is less than your job timeout."
    required: false
    default: 350m
  fuzz-minimize-time:
    description: "Fuzz minimization duration, specified as a `time.Duration` (for example `1h30s`). Corresponds to `-fuzzminimizetime` flag for the `go test` command. If you provide this input, ensure it is less than your job timeout."
    required: true
    default: 60s
  base-branch:
    description: "The base branch name of the pull request."
    required: false
  head-branch-prefix:
    description: "The prefix of the head branch name of the pull request."
    required: true
    default: "actions-go-fuzz"

outputs:
  found:
    description: "true if new crashers are found"
  head-branch:
    description: "the name of the head branch of the pull request the action created"
  pull-request-number:
    description: "the number of the pull request the action created"
  pull-request-url:
    description: "the URL of the pull request the action created"

runs:
  using: "node16"
  main: "../dist/run/index.js"
  post: "../dist/save-cache/index.js"
  post-if: "always()"
