name: "Run Fuzz Tests of Go"
description: "Run Fuzz Tests of Go"
author: "ICHINOSE Shogo"

inputs:
  repository:
    description: "The name of the repository with owner (e.g., `shogo82148/actions-go-fuzz`). It defaults to the repository where the action is running."
    required: true
    default: ${{ github.repository }}
  token:
    description: "The GitHub token for the repository. It defaults to the token provided by the GitHub Actions environment."
    required: true
    default: ${{ github.token }}
  packages:
    required: false
    description: "An optional parameter to specify the Go packages for fuzz tests. By default, it targets all packages in your project (`./...`)."
    default: "./..."
  working-directory:
    required: false
    description: "This is also an optional parameter that allows you to specify a working directory. The default is the root directory (`.`)."
    default: "."
  fuzz-regexp:
    required: false
    description: "Run the fuzz test matching the regular expression. Corresponds to the `-fuzz` flag for the `go test` command."
    default: "^Fuzz"
  fuzz-time:
    description: "Fuzz target iteration duration, specified as a `time.Duration` (for example `1h30s`). Corresponds to `-fuzztime` flag for the `go test` command. Ensure this is less than your job timeout."
    required: false
    default: 350m
  fuzz-minimize-time:
    description: "Fuzz minimization duration, specified as a `time.Duration` (for example `1h30s`). Corresponds to `-fuzzminimizetime` flag for the `go test` command. If you provide this input, ensure it is less than your job timeout."
    required: true
    default: 60s
  report-method:
    description: "The method to report the result. `pull-request` to create a pull request, `slack` to send a message via Slack Incoming Web Hook."
    required: true
    default: "pull-request"
  base-branch:
    description: "The base branch name of the pull request."
    required: false
  head-branch-prefix:
    description: "The prefix of the head branch name of the pull request."
    required: true
    default: "actions-go-fuzz"
  webhook-url:
    description: "The URL of the Slack Incoming Web Hook."
    required: false
  tags:
    required: false
    description: "A comma-separated list of additional build tags to consider satisfied during the build. It is equivalent to the `-tags` flag of the `go test` command."
    default: ""

outputs:
  found:
    description: "`true` if new crashers are found. otherwise, it is falsy value."
  head-branch:
    description: "the name of the head branch of the pull request the action created"
  pull-request-number:
    description: "the number of the pull request the action created"
  pull-request-url:
    description: "the URL of the pull request the action created"

runs:
  using: "node16"
  main: "../dist/run/index.js"
  post: "../dist/save-cache/index.js"
  post-if: "always()"
