name: "build"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

permissions:
  contents: read

jobs:
  # make sure build/ci work properly
  build:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: |
          npm ci
      - run: |
          npm run all
